<a href="https://colab.research.google.com/github/gkyr92/Test_Deep_Learning_Project/blob/master/Test_main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
import os
drive.mount('/content/gdrive')
root_path = 'gdrive/My Drive/Colab Notebooks/Kaggle'

Mounted at /content/gdrive

In [5]:
from google.colab import files
files.upload() #this will prompt you to update the json

!pip install -q kaggle
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!ls ~/.kaggle
!chmod 600 /root/.kaggle/kaggle.json  # set permission

Saving kaggle.json to kaggle (1).json
kaggle.json

In [14]:
import kaggle
!kaggle competitions download -c riiid-test-answer-prediction -p /content/gdrive/My\ Drive/Colab\ Notebooks/Kaggle/Dataset

Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.6 / client 1.5.4)
Downloading competition.cpython-37m-x86_64-linux-gnu.so to /content/gdrive/My Drive/Colab Notebooks/Kaggle/Dataset
  0% 0.00/445k [00:00<?, ?B/s]
100% 445k/445k [00:00<00:00, 29.3MB/s]
Downloading __init__.py to /content/gdrive/My Drive/Colab Notebooks/Kaggle/Dataset
  0% 0.00/59.0 [00:00<?, ?B/s]
100% 59.0/59.0 [00:00<00:00, 8.08kB/s]
Downloading questions.csv to /content/gdrive/My Drive/Colab Notebooks/Kaggle/Dataset
  0% 0.00/289k [00:00<?, ?B/s]
100% 289k/289k [00:00<00:00, 40.2MB/s]
Downloading example_test.csv to /content/gdrive/My Drive/Colab Notebooks/Kaggle/Dataset
  0% 0.00/5.99k [00:00<?, ?B/s]
100% 5.99k/5.99k [00:00<00:00, 396kB/s]
Downloading train.csv.zip to /content/gdrive/My Drive/Colab Notebooks/Kaggle/Dataset
100% 1.29G/1.29G [00:11<00:00, 87.8MB/s]
100% 1.29G/1.29G [00:11<00:00, 118MB/s]
Downloading lectures.csv to /content/gdrive/My Drive/Colab Notebooks/Kaggle/Dataset
  0% 0.00/9.48k [00:00<?, ?B/s]
100% 9.48k/9.48k [00:00<00:00, 634kB/s]
Downloading example_sample_submission.csv to /content/gdrive/My Drive/Colab Notebooks/Kaggle/Dataset
  0% 0.00/971 [00:00<?, ?B/s]
100% 971/971 [00:00<00:00, 132kB/s]

In [20]:
os.chdir('gdrive/My Drive/Colab Notebooks/Kaggle/Dataset')  #change dir
!mkdir train  #create a directory named train/
!unzip -q train.csv.zip -d train/  #unzip data in train/

In [4]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/gdrive/My Drive/Colab Notebooks/Kaggle/Dataset/train/train.csv', nrows=10000)
df.sample(20)

      row_id  ...  prior_question_had_explanation
4012    4012  ...                            True
2771    2771  ...                            True
3522    3522  ...                            True
4497    4497  ...                            True
9989    9989  ...                            True
2052    2052  ...                            True
8287    8287  ...                            True
2721    2721  ...                            True
3426    3426  ...                            True
8332    8332  ...                            True
3978    3978  ...                            True
3706    3706  ...                            True
2474    2474  ...                            True
5135    5135  ...                            True
7317    7317  ...                            True
1890    1890  ...                           False
2577    2577  ...                            True
9104    9104  ...                            True
762      762  ...                            True
5775    5775  ...                            True

[20 rows x 10 columns]